version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.8
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  logstash:
    image: logstash:7.17.8
    ports:
      - 5606:5606
    volumes:
      - /Users/Projects/SpringBoot-Tutorial/config-dir
    links:
      - elasticsearch:elasticsearch
    command: logstash -f /Users/Projects/SpringBoot-Tutorial/config-dir
  kibana:
    image: kibana:7.17.8
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch

#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'db'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'user'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'test'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'test'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '3307:3306'
#    expose:
#      # Opens port 3307 on the container
#      - '3307'
#      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
#volumes:
#  my-db: